dev:
	 poetry run python manage.py runserver
console:
	poetry run python manage.py shell --ipython
migrate:
	poetry run python manage.py makemigrations
	poetry run python manage.py migrate
superuser:
	poetry run python manage.py createsuperuser